### ISSUE TITLE
Hook crashes the game 

### ISSUE THREAD

**Issue by 19Aidan** [ermaccer/ScarfaceHook#1]
Hello! I installed the hook and put it in the root dictatory as said. I had several different mods like Remastered Project, silent patch and Optional Debug Menu. after running it simply crashes after a single second. I tested it without the hook and works fine. This is a fantastic mod and I wanted to let you know about the issue. and yes. I am on the latest version as Remastered Project works. Let me know when you have time. :)

**Comment by ermaccer** [comment]
Are you on 1.0.0.2?

**Comment by 19Aidan** [comment]
Yes.
![Screenshot 2022-08-23 041336](https://user-images.githubusercontent.com/90439269/186144237-6158d21c-0d89-473c-a5dc-acc33b34f743.png)
I believe that should be the 1.0.0.2 exe date.

**Comment by ermaccer** [comment]
Go to Properties->Details->Version and check if 1.0.0.2 is there.

**Comment by 19Aidan** [comment]
![image](https://user-images.githubusercontent.com/90439269/186277854-77906ec3-324d-4f7a-b810-3b9169443b67.png)

It should be 1.00.2 but I guess it's 1.00.1 afterall I thought it was a bug with the verison not updating. :/

**Comment by 19Aidan** [comment]
![Scarface 2022-08-24 16-00-29](https://user-images.githubusercontent.com/90439269/186538287-6a982e8f-dc1b-4c2d-a4e9-b8803aa9770a.png)
Closing this. It was my fault man. The exe was never updated to 1.00.2. sorry for wasting your time. I hope you have a good day. and keep up the good work. the hook is amazing! :)
